name: Accessibility Tests On Demand

on:
  issue_comment:

jobs:
  print-info:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "#ï¸âƒ£ github.event.issue.pull_request = ${{ github.event.issue.pull_request }}"

  accessibility-tests:
    name: Execute accessibility tests
    if: github.event.issue.pull_request && github.event.comment.body == 'please run accessibility tests'
    uses: gabalafou/jupyter-a11y-testing/.github/workflows/jlab-a11y-test.yml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.event.issue.pull_request.head.sha }}
