name: Accessibility Tests On Demand

on:
  issue_comment:

jobs:
  print-info:
    if: github.event.issue.pull_request
    needs: pr_sha_from_number
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "â˜ï¸ GitHub API Request, outputs.data = ${{ needs.pr_sha_from_number.outputs.data }}"
      - run: echo "#ï¸âƒ£ PR head sha? = ${{ fromJSON(needs.pr_sha_from_number.outputs.data).head.sha }}"

  pr_sha_from_number:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: GitHub API Request
        uses: octokit/request-action@v2.1.0
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  accessibility-tests:
    name: Execute accessibility tests
    if: github.event.issue.pull_request && github.event.comment.body == 'please run accessibility tests'
    needs: pr_sha_from_number
    uses: gabalafou/jupyter-a11y-testing/.github/workflows/jlab-a11y-test.yml@main
    with:
      repository: ${{ github.repository }}
      ref: ${{ fromJSON(needs.pr_sha_from_number.outputs.data).head.sha }}
