name: Accessibility Tests Comparison

on:
  issue_comment:

jobs:
  print-info:
    if: github.event.issue.pull_request
    needs: pr_sha_from_number
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "outputs.sha ${{ needs.pr_sha_from_number.outputs.sha }}"

  pr_sha_from_number:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    outputs:
      head_sha: ${{ fromJSON(steps.get_pr.outputs.data).head.sha }}
      base_sha: ${{ fromJSON(steps.get_pr.outputs.date).base.sha }}
    steps:
      - id: get_pr
        name: GitHub API Request
        uses: octokit/request-action@v2.1.7
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  accessibility-tests-comparison:
    name: Compare accessibility tests
    if: github.event.issue.pull_request && github.event.comment.body == 'please compare accessibility tests'
    runs-on: ubuntu-latest
    needs: pr_sha_from_number
    steps:
      - name: Write Intro to Job summary
      - run: |
          echo "Hi, it looks like you requested a comparison of" >> $GITHUB_STEPS_SUMMARY
          echo "accessibility tests for PR #${{ github.event.issue.number }}." >> $GITHUB_STEPS_SUMMARY
          echo "The tests will first be run against the base branch of the PR." >> $GITHUB_STEPS_SUMMARY
          echo "Then they will be run against the head commit of the PR." >> $GITHUB_STEPS_SUMMARY
          echo "This should allow you to see that this PR fixes an accessibility" >> $GITHUB_STEPS_SUMMARY
          echo "that has a corresponding regression test." >> $GITHUB_STEPS_SUMMARY
          echo "" >> $GITHUB_STEPS_SUMMARY
          echo "-----------" >> $GITHUB_STEPS_SUMMARY
          echo "The following test results are against the base, whose commit SHA is:" >> $GITHUB_STEPS_SUMMARY
          echo "${{ needs.pr_sha_from_number.outputs.base_sha }}"
          echo "-----------" >> $GITHUB_STEPS_SUMMARY

      - name: Run accessibility tests against base branch
        uses: gabalafou/jupyter-a11y-testing/.github/actions/jlab-a11y-test@main
        with:
          repository: ${{ github.repository }}
          ref: ${{ needs.pr_sha_from_number.base_sha }}

      - name: Intro second run
        run: |
          echo "-----------" >> $GITHUB_STEPS_SUMMARY
          echo "The following test results are against this PR, whose head commit SHA is:" >> $GITHUB_STEPS_SUMMARY
          echo "${{ needs.pr_sha_from_number.outputs.head_sha }}"
          echo "-----------" >> $GITHUB_STEPS_SUMMARY

      - name: Run accessibility tests against base branch
        uses: gabalafou/jupyter-a11y-testing/.github/actions/jlab-a11y-test@main
        with:
          repository: ${{ github.repository }}
          ref: ${{ needs.pr_sha_from_number.head_sha }}
